# Generated by Django 6.0.3 on 2026-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("point", "Point"),
                            ("line", "Line"),
                            ("polygon", "Polygon"),
                        ],
                        default="point",
                        max_length=10,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        help_text="Raw coordinates: [lon, lat] for point, [[lon,lat],...] for line/polygon"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
