# Generated by Django 6.0.3 on 2026-03-13 17:09

from django.db import migrations


def deduplicate_locations(apps, schema_editor):
    Location = apps.get_model("api", "Location")
    seen: set[tuple] = set()
    for loc in Location.objects.order_by("created_at"):
        key = (loc.name, loc.latitude, loc.longitude)
        if key in seen:
            loc.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(deduplicate_locations, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name", "latitude", "longitude")},
        ),
    ]
