# Generated by Django 6.0.3 on 2026-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_unique_location_name_coords"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="wikidata_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
