# Generated by Django 6.0.3 on 2026-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_location_wikidata_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HikeRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "waypoints",
                    models.JSONField(help_text="[[lon, lat], ...] user control points"),
                ),
                (
                    "geometry",
                    models.JSONField(
                        help_text="[[lon, lat], ...] ORS LineString coordinates"
                    ),
                ),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
