# Generated by Django 6.0.3 on 2026-03-14 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_hike_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("name", models.CharField(default="My Trip", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="hikeroute",
            name="map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hike_routes",
                to="api.map",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="api.map",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("map", "name", "latitude", "longitude")},
        ),
    ]
