# Generated by Django 6.0.3 on 2026-03-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_assign_locations_to_map_one"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationIsochroneCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(help_text="Lat used for the isochrone request"),
                ),
                (
                    "longitude",
                    models.FloatField(help_text="Lon used for the isochrone request"),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Normalized FeatureCollection from ORS/Valhalla"
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isochrone_cache",
                        to="api.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationReachabilityCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Reachability response: type, origin, features"
                    ),
                ),
                (
                    "query_datetime",
                    models.DateTimeField(
                        help_text="Departure time used for the Transitous query (UTC)"
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reachability_cache",
                        to="api.location",
                    ),
                ),
            ],
        ),
    ]
