# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_hikeroute_elevation"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
