# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_location_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationreachabilitycache",
            name="location",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="reachability_cache",
                to="api.location",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationreachabilitycache",
            constraint=models.UniqueConstraint(
                fields=("location", "query_datetime"),
                name="unique_location_query_datetime",
            ),
        ),
    ]
