# Generated by Django 6.0.3 on 2026-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_locationreachabilitycache_unique_location_query_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationreachabilitycache",
            name="query_datetime",
            field=models.DateTimeField(
                help_text="Departure time or window start used for the query (UTC)"
            ),
        ),
    ]
