# Generated by Django 6.0.3 on 2026-03-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_locationreachabilitycache_query_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachabilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('query_datetime', models.DateTimeField(help_text='Departure time used for the query (UTC)')),
                ('data', models.JSONField(help_text='Reachability response: type, origin, features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='locationreachabilitycache',
            name='unique_location_query_datetime',
        ),
        migrations.AddConstraint(
            model_name='reachabilitycache',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude', 'query_datetime'), name='unique_reachability_coords_datetime'),
        ),
        migrations.DeleteModel(
            name='LocationReachabilityCache',
        ),
    ]
