# Generated by Django 6.0.3 on 2026-03-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_replace_locationreachabilitycache_with_reachabilitycache"),
    ]

    operations = [
        migrations.AddField(
            model_name="hikeroute",
            name="color",
            field=models.CharField(blank=True, default="#1565c0", max_length=20),
        ),
    ]
